apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'flask-app'
        static_configs:
          - targets: ['flask-app-service:5000']  # Replace with your Flask app service name

      - job_name: 'postgres-db'
        static_configs:
          - targets: ['postgres-db-service:5432']  # Replace with your Postgres db service name
